/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_exlmoto_qmldestroytest_NativeHelper */

#ifndef _Included_ru_exlmoto_qmldestroytest_NativeHelper
#define _Included_ru_exlmoto_qmldestroytest_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_exlmoto_qmldestroytest_NativeHelper
 * Method:    invokeVoidMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_qmldestroytest_NativeHelper_invokeVoidMethod
  (JNIEnv *, jclass, jint);

/*
 * Class:     ru_exlmoto_qmldestroytest_NativeHelper
 * Method:    sendMockLocationDataToQml
 * Signature: (IDDD)V
 */
JNIEXPORT void JNICALL Java_ru_exlmoto_qmldestroytest_NativeHelper_sendMockLocationDataToQml
  (JNIEnv *, jclass, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
